name: cubit_pool
description: "A new Flutter package project."
version: 1.1.2
homepage: null

environment:
  sdk: ">=3.8.0"

publish_to: none

dependencies:
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.7
  equatable: ^2.0.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  source_gen: ^3.0.0

flutter: null
